use serde::Serialize;

use crate::error::{KrxCliError, Result};

const IDX_12_FIELDS: &[&str] = &[
    "BAS_DD",
    "IDX_CLSS",
    "IDX_NM",
    "CLSPRC_IDX",
    "CMPPREVDD_IDX",
    "FLUC_RT",
    "OPNPRC_IDX",
    "HGPRC_IDX",
    "LWPRC_IDX",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
];
const IDX_BOND_15_FIELDS: &[&str] = &[
    "BAS_DD",
    "BND_IDX_GRP_NM",
    "TOT_EARNG_IDX",
    "TOT_EARNG_IDX_CMPPREVDD",
    "NETPRC_IDX",
    "NETPRC_IDX_CMPPREVDD",
    "ZERO_REINVST_IDX",
    "ZERO_REINVST_IDX_CMPPREVDD",
    "CALL_REINVST_IDX",
    "CALL_REINVST_IDX_CMPPREVDD",
    "MKT_PRC_IDX",
    "MKT_PRC_IDX_CMPPREVDD",
    "AVG_DURATION",
    "AVG_CONVEXITY_PRC",
    "BND_IDX_AVG_YD",
];
const IDX_DERIVATIVE_9_FIELDS: &[&str] = &[
    "BAS_DD",
    "IDX_CLSS",
    "IDX_NM",
    "CLSPRC_IDX",
    "CMPPREVDD_IDX",
    "FLUC_RT",
    "OPNPRC_IDX",
    "HGPRC_IDX",
    "LWPRC_IDX",
];
const STOCK_15_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISU_CD",
    "ISU_NM",
    "MKT_NM",
    "SECT_TP_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
    "LIST_SHRS",
];
const SW_20_FIELDS: &[&str] = &[
    "BAS_DD",
    "MKT_NM",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
    "LIST_SHRS",
    "EXER_PRC",
    "EXST_STRT_DD",
    "EXST_END_DD",
    "TARSTK_ISU_SRT_CD",
    "TARSTK_ISU_NM",
    "TARSTK_ISU_PRSNT_PRC",
];
const SR_19_FIELDS: &[&str] = &[
    "BAS_DD",
    "MKT_NM",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
    "LIST_SHRS",
    "ISU_PRC",
    "DELIST_DD",
    "TARSTK_ISU_SRT_CD",
    "TARSTK_ISU_NM",
    "TARSTK_ISU_PRSNT_PRC",
];
const ISU_BASE_12_FIELDS: &[&str] = &[
    "ISU_CD",
    "ISU_SRT_CD",
    "ISU_NM",
    "ISU_ABBRV",
    "ISU_ENG_NM",
    "LIST_DD",
    "MKT_TP_NM",
    "SECUGRP_NM",
    "SECT_TP_NM",
    "KIND_STKCERT_TP_NM",
    "PARVAL",
    "LIST_SHRS",
];
const ETF_19_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "NAV",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
    "INVSTASST_NETASST_TOTAMT",
    "LIST_SHRS",
    "IDX_IND_NM",
    "OBJ_STKPRC_IDX",
    "CMPPREVDD_IDX",
    "FLUC_RT_IDX",
];
const ETN_19_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "PER1SECU_INDIC_VAL",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
    "INDIC_VAL_AMT",
    "LIST_SHRS",
    "IDX_IND_NM",
    "OBJ_STKPRC_IDX",
    "CMPPREVDD_IDX",
    "FLUC_RT_IDX",
];
const ELW_16_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "MKTCAP",
    "LIST_SHRS",
    "ULY_NM",
    "ULY_PRC",
    "CMPPREVDD_PRC_ULY",
    "FLUC_RT_ULY",
];
const KTS_17_FIELDS: &[&str] = &[
    "BAS_DD",
    "MKT_NM",
    "ISU_CD",
    "ISU_NM",
    "BND_EXP_TP_NM",
    "GOVBND_ISU_TP_NM",
    "CLSPRC",
    "CMPPREVDD_PRC",
    "CLSPRC_YD",
    "OPNPRC",
    "OPNPRC_YD",
    "HGPRC",
    "HGPRC_YD",
    "LWPRC",
    "LWPRC_YD",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
];
const BND_15_FIELDS: &[&str] = &[
    "BAS_DD",
    "MKT_NM",
    "ISU_CD",
    "ISU_NM",
    "CLSPRC",
    "CMPPREVDD_PRC",
    "CLSPRC_YD",
    "OPNPRC",
    "OPNPRC_YD",
    "HGPRC",
    "HGPRC_YD",
    "LWPRC",
    "LWPRC_YD",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
];
const FUTURE_15_FIELDS: &[&str] = &[
    "BAS_DD",
    "PROD_NM",
    "MKT_NM",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "SPOT_PRC",
    "SETL_PRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "ACC_OPNINT_QTY",
];
const OPTION_15_FIELDS: &[&str] = &[
    "BAS_DD",
    "PROD_NM",
    "RGHT_TP_NM",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "IMP_VOLT",
    "NXTDD_BAS_PRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
    "ACC_OPNINT_QTY",
];
const OIL_6_FIELDS: &[&str] = &[
    "BAS_DD",
    "OIL_NM",
    "WT_AVG_PRC",
    "WT_DIS_AVG_PRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
];
const GEN_11_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISU_CD",
    "ISU_NM",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "TDD_OPNPRC",
    "TDD_HGPRC",
    "TDD_LWPRC",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
];
const ESG_ETP_8_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISU_ABBRV",
    "TDD_CLSPRC",
    "CMPPREVDD_PRC",
    "FLUC_RT",
    "LIST_SHRS",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
];
const SRI_BOND_12_FIELDS: &[&str] = &[
    "BAS_DD",
    "ISUR_NM",
    "ISU_CD",
    "SRI_BND_TP_NM",
    "ISU_NM",
    "LIST_DD",
    "ISU_DD",
    "REDMPT_DD",
    "ISU_RT",
    "ISU_AMT",
    "LIST_AMT",
    "BND_TP_NM",
];
const ESG_INDEX_8_FIELDS: &[&str] = &[
    "BAS_DD",
    "IDX_NM",
    "CLSPRC_IDX",
    "PRV_DD_CMPR",
    "UPDN_RATE",
    "TRD_ISU_CNT",
    "ACC_TRDVOL",
    "ACC_TRDVAL",
];

#[derive(Debug, Clone, Copy)]
pub struct ApiSpec {
    pub category: &'static str,
    pub api_id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub path: &'static str,
    pub bas_dd_example: Option<&'static str>,
    pub output_fields: usize,
    pub output_field_names: &'static [&'static str],
}

impl ApiSpec {
    pub fn sample_endpoint(&self, format: &str) -> String {
        format!(
            "https://data-dbg.krx.co.kr/svc/sample/apis/{}/{}.{}",
            self.path, self.api_id, format
        )
    }

    pub fn real_endpoint(&self) -> String {
        format!(
            "https://data-dbg.krx.co.kr/svc/apis/{}/{}",
            self.path, self.api_id
        )
    }
}

#[derive(Debug, Serialize)]
pub struct ApiSchemaView<'a> {
    pub category: &'a str,
    pub api_id: &'a str,
    pub name: &'a str,
    pub description: &'a str,
    pub path: &'a str,
    pub sample_endpoint: String,
    pub real_endpoint: String,
    pub query_parameters: Vec<QueryParameterView<'a>>,
    pub output_fields: usize,
    pub output_field_names: &'a [&'a str],
}

#[derive(Debug, Serialize)]
pub struct QueryParameterView<'a> {
    pub name: &'a str,
    pub description: &'a str,
    pub required: bool,
    pub example: Option<&'a str>,
}

impl<'a> From<&'a ApiSpec> for ApiSchemaView<'a> {
    fn from(value: &'a ApiSpec) -> Self {
        Self {
            category: value.category,
            api_id: value.api_id,
            name: value.name,
            description: value.description,
            path: value.path,
            sample_endpoint: value.sample_endpoint("json"),
            real_endpoint: value.real_endpoint(),
            query_parameters: vec![QueryParameterView {
                name: "basDd",
                description: "기준일자 (YYYYMMDD)",
                required: true,
                example: value.bas_dd_example,
            }],
            output_fields: value.output_fields,
            output_field_names: value.output_field_names,
        }
    }
}

pub fn list_apis() -> &'static [ApiSpec] {
    APIS
}

pub fn find_api(api_id: &str) -> Result<&'static ApiSpec> {
    APIS.iter()
        .find(|api| api.api_id == api_id)
        .ok_or_else(|| KrxCliError::UnknownApi(api_id.to_string()))
}

static APIS: &[ApiSpec] = &[
    ApiSpec {
        category: "지수",
        api_id: "krx_dd_trd",
        name: "KRX 시리즈 일별시세정보",
        description: "KRX 시리즈 지수의 시세정보 제공",
        path: "idx",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: IDX_12_FIELDS,
    },
    ApiSpec {
        category: "지수",
        api_id: "kospi_dd_trd",
        name: "KOSPI 시리즈 일별시세정보",
        description: "KOSPI 시리즈 지수의 시세정보 제공",
        path: "idx",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: IDX_12_FIELDS,
    },
    ApiSpec {
        category: "지수",
        api_id: "kosdaq_dd_trd",
        name: "KOSDAQ 시리즈 일별시세정보",
        description: "KOSDAQ 시리즈 지수의 시세정보 제공",
        path: "idx",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: IDX_12_FIELDS,
    },
    ApiSpec {
        category: "지수",
        api_id: "bon_dd_trd",
        name: "채권지수 시세정보",
        description: "채권지수의 시세정보 제공",
        path: "idx",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: IDX_BOND_15_FIELDS,
    },
    ApiSpec {
        category: "지수",
        api_id: "drvprod_dd_trd",
        name: "파생상품지수 시세정보",
        description: "파생상품지수의 시세정보 제공",
        path: "idx",
        bas_dd_example: Some("20200414"),
        output_fields: 9,
        output_field_names: IDX_DERIVATIVE_9_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "stk_bydd_trd",
        name: "유가증권 일별매매정보",
        description: "유가증권시장 상장 주권의 매매정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: STOCK_15_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "ksq_bydd_trd",
        name: "코스닥 일별매매정보",
        description: "코스닥시장 상장 주권의 매매정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: STOCK_15_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "knx_bydd_trd",
        name: "코넥스 일별매매정보",
        description: "코넥스시장 상장 주권의 매매정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: STOCK_15_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "sw_bydd_trd",
        name: "신주인수권증권 일별매매정보",
        description: "신주인수권증권의 매매정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 20,
        output_field_names: SW_20_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "sr_bydd_trd",
        name: "신주인수권증서 일별매매정보",
        description: "신주인수권증서의 매매정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 19,
        output_field_names: SR_19_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "stk_isu_base_info",
        name: "유가증권 종목기본정보",
        description: "유가증권 종목기본정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: ISU_BASE_12_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "ksq_isu_base_info",
        name: "코스닥 종목기본정보",
        description: "코스닥 종목기본정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: ISU_BASE_12_FIELDS,
    },
    ApiSpec {
        category: "주식",
        api_id: "knx_isu_base_info",
        name: "코넥스 종목기본정보",
        description: "코넥스 종목기본정보 제공",
        path: "sto",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: ISU_BASE_12_FIELDS,
    },
    ApiSpec {
        category: "증권상품",
        api_id: "etf_bydd_trd",
        name: "ETF 일별매매정보",
        description: "ETF 매매정보 제공",
        path: "etp",
        bas_dd_example: Some("20200414"),
        output_fields: 19,
        output_field_names: ETF_19_FIELDS,
    },
    ApiSpec {
        category: "증권상품",
        api_id: "etn_bydd_trd",
        name: "ETN 일별매매정보",
        description: "ETN 매매정보 제공",
        path: "etp",
        bas_dd_example: Some("20200414"),
        output_fields: 19,
        output_field_names: ETN_19_FIELDS,
    },
    ApiSpec {
        category: "증권상품",
        api_id: "elw_bydd_trd",
        name: "ELW 일별매매정보",
        description: "ELW 매매정보 제공",
        path: "etp",
        bas_dd_example: Some("20200414"),
        output_fields: 16,
        output_field_names: ELW_16_FIELDS,
    },
    ApiSpec {
        category: "채권",
        api_id: "kts_bydd_trd",
        name: "국채전문유통시장 일별매매정보",
        description: "국채전문유통시장 매매정보 제공",
        path: "bon",
        bas_dd_example: Some("20200414"),
        output_fields: 17,
        output_field_names: KTS_17_FIELDS,
    },
    ApiSpec {
        category: "채권",
        api_id: "bnd_bydd_trd",
        name: "일반채권시장 일별매매정보",
        description: "일반채권시장 매매정보 제공",
        path: "bon",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: BND_15_FIELDS,
    },
    ApiSpec {
        category: "채권",
        api_id: "smb_bydd_trd",
        name: "소액채권시장 일별매매정보",
        description: "소액채권시장 매매정보 제공",
        path: "bon",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: BND_15_FIELDS,
    },
    ApiSpec {
        category: "파생상품",
        api_id: "fut_bydd_trd",
        name: "선물 일별매매정보 (주식선물外)",
        description: "주식선물 외 선물 매매정보 제공",
        path: "drv",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: FUTURE_15_FIELDS,
    },
    ApiSpec {
        category: "파생상품",
        api_id: "eqsfu_stk_bydd_trd",
        name: "주식선물(유가) 일별매매정보",
        description: "유가 시장 기초자산 주식선물 거래정보 제공",
        path: "drv",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: FUTURE_15_FIELDS,
    },
    ApiSpec {
        category: "파생상품",
        api_id: "eqkfu_ksq_bydd_trd",
        name: "주식선물(코스닥) 일별매매정보",
        description: "코스닥 기초자산 주식선물 거래정보 제공",
        path: "drv",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: FUTURE_15_FIELDS,
    },
    ApiSpec {
        category: "파생상품",
        api_id: "opt_bydd_trd",
        name: "옵션 일별매매정보 (주식옵션外)",
        description: "주식옵션 외 옵션 매매정보 제공",
        path: "drv",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: OPTION_15_FIELDS,
    },
    ApiSpec {
        category: "파생상품",
        api_id: "eqsop_bydd_trd",
        name: "주식옵션(유가) 일별매매정보",
        description: "유가 시장 기초자산 주식옵션 거래정보 제공",
        path: "drv",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: OPTION_15_FIELDS,
    },
    ApiSpec {
        category: "파생상품",
        api_id: "eqkop_bydd_trd",
        name: "주식옵션(코스닥) 일별매매정보",
        description: "코스닥 기초자산 주식옵션 거래정보 제공",
        path: "drv",
        bas_dd_example: Some("20200414"),
        output_fields: 15,
        output_field_names: OPTION_15_FIELDS,
    },
    ApiSpec {
        category: "일반상품",
        api_id: "oil_bydd_trd",
        name: "석유시장 일별매매정보",
        description: "KRX 석유시장 매매정보 제공",
        path: "gen",
        bas_dd_example: Some("20200414"),
        output_fields: 6,
        output_field_names: OIL_6_FIELDS,
    },
    ApiSpec {
        category: "일반상품",
        api_id: "gold_bydd_trd",
        name: "금시장 일별매매정보",
        description: "KRX 금시장 매매정보 제공",
        path: "gen",
        bas_dd_example: Some("20200414"),
        output_fields: 11,
        output_field_names: GEN_11_FIELDS,
    },
    ApiSpec {
        category: "일반상품",
        api_id: "ets_bydd_trd",
        name: "배출권 시장 일별매매정보",
        description: "KRX 배출권 시장 매매정보 제공",
        path: "gen",
        bas_dd_example: Some("20200414"),
        output_fields: 11,
        output_field_names: GEN_11_FIELDS,
    },
    ApiSpec {
        category: "ESG",
        api_id: "esg_etp_info",
        name: "ESG 증권상품",
        description: "ESG 증권상품 정보 제공",
        path: "esg",
        bas_dd_example: None,
        output_fields: 8,
        output_field_names: ESG_ETP_8_FIELDS,
    },
    ApiSpec {
        category: "ESG",
        api_id: "sri_bond_info",
        name: "사회책임투자채권 정보",
        description: "사회책임투자채권 정보 제공",
        path: "esg",
        bas_dd_example: Some("20200414"),
        output_fields: 12,
        output_field_names: SRI_BOND_12_FIELDS,
    },
    ApiSpec {
        category: "ESG",
        api_id: "esg_index_info",
        name: "ESG 지수",
        description: "ESG 지수 정보 제공",
        path: "esg",
        bas_dd_example: None,
        output_fields: 8,
        output_field_names: ESG_INDEX_8_FIELDS,
    },
];

#[cfg(test)]
mod tests {
    use super::{ApiSchemaView, find_api};

    #[test]
    fn schema_view_includes_output_field_names() {
        let api = find_api("krx_dd_trd").unwrap();
        let view = ApiSchemaView::from(api);

        assert_eq!(view.output_fields, view.output_field_names.len());
        assert_eq!(view.output_field_names[0], "BAS_DD");
        assert!(view.output_field_names.contains(&"IDX_NM"));
    }
}
